# Generated by Django 3.2.9 on 2022-01-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='departments',
            new_name='department',
        ),
    ]
